### ISSUE TITLE
Yet another implementation in Rust

### ISSUE THREAD

**Issue by hermes85pl** [petersmagnusson/base62#1]
You might consider adding https://github.com/fbernier/base62 that I came across to the list of other implementations.

Additionally, I would suggest mentioning the language that is used by the referenced implementations, as I think it would be helpful to the readers.

By the way, thank you for the great summary and remarks in the README.

**Comment by petersmagnusson** [comment]
Done, and done. And thx!

**Comment by petersmagnusson** [comment]
Committed.

**Comment by petersmagnusson** [comment]
@hermes85pl - just fyi, in case you're interested, I've added a Rust version.
